### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by olikraus** [olikraus/c-object#1]
- [x] JSON write: Add proper escapes, UTF8 support
 - [x] test json write
 - [x] BOM detection, create a commen procedure like getAndSkipBOM(FILE *fp)
 - [x] Binary Data object

BOM (https://en.wikipedia.org/wiki/Byte_order_mark)
		UTF-8 	EF BB BF
		UTF-16 (BE) 	FE FF
		UTF-16 (LE) 	FF FE
		UTF-32 (BE) 	00 00 FE FF
		UTF-32 (LE) 	FF FE 00 00
